name: Transaction App

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  schedule:
      - cron: '0 7,10 * * 0-2'  # Runs at 3 PM & 5 PM BD Time (UTC+6), from Sunday to Thursday

permissions: 
  contents: write # Grants GitHub Actions write access

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full commit history is fetched

      - name: Set up Git User
        run: |
          git config --global user.name "prodipsb"
          git config --global user.email "prodip5080@gmail.com"

      - name: Pull latest changes (Force Sync)
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fd

      - name: Make a commit
        run: |
          echo "Last commit $(date)" >> auth-commit-log.txt
          git add auth-commit-log.txt
          git commit -m "Transaction App commit on $(date)" || exit 0

      - name: Push changes
        run: | 
          git push origin main
